spring:
  datasource:
    url: jdbc:mysql://mysql:3306/docker-test
    username: default
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

#server:
#  servlet:
#    context-path: /spring-app
